#!/usr/bin/python

# operators in precedence order
INFIX_LEVEL = {
	"=":   0,
	"|":   1,
	"^":   2,
	"&":   3,
	"==":  4,
	"!=":  5,
	"<":   7,
	">":   7,
	"<=":  9,
	">=":  9,
	"<<": 11,
	">>": 11,
	"+":  13,
	"-":  13,
	"*":  16,
	"/":  16,
	"%":  16,
}

STMT_TYPES = [
	"block",
	"return",
]

EXPR_TYPES = INFIX_LEVEL.keys() + [
	"number",
	"neg",
	"not",
	"call",
	"use",
]


class Node:

	def __init__(self, type):
		self.type = type
		self.kids = []
		self.parent = None

	def add(self, kid):
		kid.parent = self
		self.kids.append(kid)
		return self

	def pretty_print(self, indent=0):
		line = " " * indent + self.type
		if hasattr(self, "name"):   line += " %r" % self.name
		if hasattr(self, "number"): line += " %d" % self.number
		if hasattr(self, "t"): line += " t=%s" % self.t
		print line
		for k in self.kids:
			k.pretty_print(indent + 1)

	def is_stmt(self): return self.type in STMT_TYPES
	def is_expr(self): return self.type in EXPR_TYPES


KEYWORDS = [
	"return",
	"if",
	"else",
	"while",
]


class Lexer:
	def __init__(self, code):
		self._code = code
		self._pos  = 0

		self.tok  = ""
		self.name = ""
		self.number  = 0

		self.next()

	def next(self): self.tok = self.scan()

	def char(self): return self._code[self._pos : self._pos + 1]

	def scan(self):
		while self._pos < len(self._code):
			c = self._code[self._pos]
			self._pos += 1

			if c.isalpha() or c == '_':
				self.name = c
				while self.char().isalnum() or self.char() == '_':
					self.name += self._code[self._pos]
					self._pos += 1
				if self.name in KEYWORDS: return self.name
				return "id"

			if c.isdigit():
				self.number = int(c)
				while self.char().isdigit():
					self.number = self.number * 10 + int(self._code[self._pos])
					self._pos += 1
				return "number"

			if c in "+-*%(){};~": return c
			if c == "/":
				if self.char() != '/': return "/";
				while self._pos < len(self._code) and self._code[self._pos] != "\n":
					self._pos += 1
				continue

			if c in "<>":
				if self.char() not in c + "=": return c
				self._pos += 1
				return c + self.char()

			if c in "!=":
				if self.char() != "=": return c
				self._pos += 1
				return c + "="

			assert c.isspace(), "unexpected character %r" % c

		return ""



class Parser(Lexer):
	def __init__(self, code):
		Lexer.__init__(self, code)

	def parse(self):

		prog = Node("program")

		while self.tok:

			# read type and name
			t = self.name
			self.match("id")
			n = self.name
			self.match("id")

			# function
			if self.tok == "(":
				self.next()
				node = Node("func")
				assert t in ("void", "int"), "invalid type"
				node.t = t
				node.name = n
				# TODO: arguments
				self.match(")")
				assert self.tok == "{", "no function block"

				node.add(self.stmt())
				prog.add(node)
				continue

			# variable
			assert t in ("int"), "invalid type"
			node = Node("var")
			node.t = t
			node.name = n
			self.match(";")
			prog.add(node)
			continue

		return prog

	def stmt(self):
		if self.tok == "return":
			self.next()
			node = Node("return")
			if self.tok != ";": node.add(self.expr())
			self.match(";")
			return node
		elif self.tok == "{":
			self.next()
			node = Node("block")
			while self.tok != "}": node.add(self.stmt())
			self.next()
			return node
		else:
			node = self.expr()
			self.match(";")
			return node

	def expr(self, level=0):

		# unary stuff
		if self.tok == "number":
			self.next()
			node = Node("number")
			node.number = self.number
		elif self.tok == "+":
			self.next()
			node = self.expr(99)
		elif self.tok == "-":
			self.next()
			node = Node("neg").add(self.expr(99))
		elif self.tok == "(":
			self.next()
			node = self.expr()
			self.match(")")
		elif self.tok == "!":
			self.next()
			node = Node("not").add(self.expr(99))
		elif self.tok == "id":
			self.next()
			if self.tok == "(":
				node = Node("call")
				node.name = self.name
				self.next()
				# TODO: args
				self.match(")")
			else:
				node = Node("use")
				node.name = self.name
		else:
			assert False, "bad expression %r" % self.tok

		# infix stuff
		while self.tok in INFIX_LEVEL and INFIX_LEVEL[self.tok] >= level:
			tok = self.tok
			self.next()
			node = Node(tok).add(node).add(self.expr(INFIX_LEVEL[tok] + 1))
		return node

	def match(self, tok):
		assert tok == self.tok, "unexpected token %r (should be %r)" % (tok, self.tok)
		self.next()



def resolve_names(node):
	for k in node.kids: resolve_names(k)

	if node.type == "use":
		n = node
		while n.parent:
			kid = n
			n = n.parent
		for k in n.kids:
			assert k != kid, "use of undefined variable %r" % node.name
			if k.type == "var" and k.name == node.name:
				node.var = k
				break

	elif node.type == "call":
		n = node
		while n.parent: n = n.parent
		for k in n.kids:
			if k.type == "func" and k.name == node.name:
				node.func = k
				break
		else:
			assert False, "call of undefined function %r" % node.name


def check_types(node):
	for k in node.kids: check_types(k)
	if not node.is_expr(): return

	if   node.type == "number": node.t = "int"
	elif node.type == "use":    node.t = node.var.t
	elif node.type == "call":   node.t = node.func.t
	#...


if __name__ == "__main__":

	code = file("test.c").read()
	ast = Parser(code).parse()
	resolve_names(ast)
	check_types(ast)
	ast.pretty_print()

